"""priority

Revision ID: 010dac239a62
Revises: 1ae716cd2e58
Create Date: 2024-06-02 23:55:09.715845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010dac239a62'
down_revision = '1ae716cd2e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subtask_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.Enum('low', 'medium', 'high', 'severe'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subtask_association', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
